### ISSUE TITLE
[Next API routes] as firebase Functions?

### ISSUE THREAD

**Issue by Beethoven** [FirebaseExtended/firebase-framework-tools#12]
It will be possible to use api routes in NextJs?
https://nextjs.org/docs/api-routes/introduction

**Comment by jamesdaniels** [comment]
Yeah, it should work out of box. If you have any troubles let us know.

**Comment by Beethoven** [comment]
Sorry guys, but I couldn't figure out how to do it.
Inside api-route you have to write an Firebase Cloud function like:

// The Cloud Functions for Firebase SDK to create Cloud Functions and set up triggers.
const functions = require('firebase-functions');

// The Firebase Admin SDK to access Firestore.
const admin = require('firebase-admin');
admin.initializeApp();
