### ISSUE TITLE
NextJS site not getting deployed when having multi-site options

### ISSUE THREAD

**Issue by fahadahmed** [FirebaseExtended/firebase-framework-tools#15]
[](url)Issue:
trying to get a next.js site deployed to firebase hosting when having 2 sites configured.

```json
"hosting": [
    {
      "target": "web",
      "public": "apps/web/public",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    },
    {
      "target": "app",
      "source": "apps/app/.",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    }
  ],
```

Error received:
`Error: An unexpected error has occurred`

![Screen Shot 2022-05-30 at 3 57 35 pm](https://user-images.githubusercontent.com/1190340/170926570-8b379612-44c7-4960-945d-d770fe4ac048.png)

I am using lerna for monorepo approach and the nextjs app is inside `app` package. This approach works when there is only one site to deploy but fails in multi-site hosting when we add the `target` attribute.

**Comment by kirupa** [comment]
@jamesdaniels - thoughts?

**Comment by jamesdaniels** [comment]
@fahadahmed do you see a firebase-debug log? If so would you mind sharing, right now the tooling is swallowing many exceptions under `An unexpected error has occured`. I need to float more to the surface.

**Comment by fahadahmed** [comment]
I probably need to regenerate the log to share. Will provide soon.

**Comment by jamesdaniels** [comment]
Ah that's helpful thanks.

**Comment by abMarlim** [comment]
> Ah that's helpful thanks.

Hey @jamesdaniels, do you think there is any workaround for now?

**Comment by noga-dev** [comment]
Trying to run a Next.js starter project and getting the same error. Also dupe in path.

```
[debug] [2022-07-24T08:53:44.098Z] Error: ENOENT: no such file or directory, open 'D:\Source\challenges\jg\hack\public\main\public\main\package.json'
```

Note the double ```public\main```.

**Comment by jamesdaniels** [comment]
We've fixed some bugs with path detection, can you confirm if we've addressed the bug with the latest generation of the tooling? https://firebase.google.com/docs/hosting/frameworks-overview

**Comment by abMarlim** [comment]
Hey @jamesdaniels Thanks for the update! Of course, I will test this next weekend and I'll let you know here, thanks for your work 🥳
