### ISSUE TITLE
NextJS site not being detected without optional next.config.js

### ISSUE THREAD

**Issue by shangyilim** [FirebaseExtended/firebase-framework-tools#19]
Tried to take frameworkaware for a spin with a sample next.js site from the guides: https://nextjs.org/learn/basics/create-nextjs-app/setup , but `firebase serve` and `firebase deploy`did not detect the framework even even after `firebase --open-sesame frameworkawareness`. 

Upon digging, turns out we need to include `next.config.js` which is not part of the setup from the sample app in the guide.
I added a empty `next.config.js` and  both `firebase serve` and `firebase deploy` worked like a charm.

I think we need to mention this in the README or we have to figure out a different way to detect the framework type?

**Comment by jamesdaniels** [comment]
Thanks for the feedback, I'll have to stew on this.

**Comment by jamesdaniels** [comment]
In the latest version of the tooling the next.config.js is now optional, so long as next is a top-level dep in your package.json
