### ISSUE TITLE
Astro support

### ISSUE THREAD

**Issue by noga-dev** [FirebaseExtended/firebase-framework-tools#25]
Since there's currently no documentation is there a quick rundown for how to get Astro SSR working with Firebase? [(There's already support for Vercel, Netlify, Node.js, Cloudflare, and Deno.)](https://docs.astro.build/en/guides/server-side-rendering/#overview)

**Comment by davideast** [comment]
We have this on our roadmap! For now you can use [astro-firebase](https://npm.im/astro-firebase).

**Comment by noga-dev** [comment]
> We have this on our roadmap! For now you can use [astro-firebase](https://npm.im/astro-firebase).

Unfortunately that package isn't being maintained and it's been broken for a while.

**Comment by jamesdaniels** [comment]
Astro is moving to Vite, since we have first-class Vite support in firebase-tools now it will be supported (for non-SSR use cases ATM) out of box. We'll look into a deeper integration in the future.
