### ISSUE TITLE
Next.js deploy site without styles 

### ISSUE THREAD

**Issue by ABDERRAHMANE-OUALI** [FirebaseExtended/firebase-framework-tools#26]
when I deploy the site the styles are gone somehow, why is that ?

**Comment by davideast** [comment]
Hey! @ABDERRAHMANE-OUALI. Can you provide more information and perhaps some example?

**Comment by jamesdaniels** [comment]
Can you confirm this is an issue in the latest version of the tooling? https://firebase.google.com/docs/hosting/nextjs If I were to guess, your content was falling back entirely to the Cloud Function. Closing until further information provided, we can reopen once we confirm it's still an issue.
