### ISSUE TITLE
Is the readme inaccurate?

### ISSUE THREAD

**Issue by subimage** [FirebaseExtended/firebase-framework-tools#28]
[Official Firebase documentation](https://firebase.google.com/docs/hosting/test-preview-deploy) recommends to use the command `firebase emulators:start` over `firebase serve`. Should the documentation be updated to reflect that?

**Comment by jamesdaniels** [comment]
We've started moving to emulators:start in the production docs https://firebase.google.com/docs/hosting/frameworks-overview

**Comment by jamesdaniels** [comment]
Thanks for reporting the inconsistency
