### ISSUE TITLE
Vite for Meta-frameworks - SvelteKit - SolidStart - QwikCity

### ISSUE THREAD

**Issue by jthegedus** [FirebaseExtended/firebase-framework-tools#32]
Hi all, I originally requested and volunteered to help with the SvelteKit integration in https://github.com/FirebaseExtended/firebase-framework-tools/issues/17

Since raising that issue, [SvelteKit](https://kit.svelte.dev/) has changed from a wrapper over top of Vite to a raw Vite plugin. Since learning this, I have also discovered the meta-frameworks for [SolidJS](https://www.solidjs.com/) ([SolidStart](https://github.com/solidjs/solid-start)) and [Qwik](https://qwik.builder.io/docs/overview/) ([QwikCity](https://qwik.builder.io/qwikcity/overview/)) are also Vite plugins as opposed to their own thing.

So, once Vite is supported in (https://github.com/firebase/firebase-tools/pull/4868 ???) it should be relatively easy to support each of these Meta Frameworks.

Just wanted to share some info should it not be known.

**Comment by jamesdaniels** [comment]
Thanks for updating. Shout out to @davideast who did the vite integration

**Comment by johnnyoshika** [comment]
Very interesting

**Comment by jamesdaniels** [comment]
Vite has been integrated with the latest generation of the tooling, frameworks that use Vite should "just work" for non-SSR ATM. We'll be looking into deeper integrations.
