### ISSUE TITLE
How do I set environment variables?

### ISSUE THREAD

**Issue by the-red** [FirebaseExtended/firebase-framework-tools#36]
I have created an `.env` file and deployed it to firebase,
but the environment variables are not enabled at the deployment location.

When I run `firebase serve` on the localhost, the environment variable is enabled.

How do I set the environment variable at the deployment location?

**Comment by agdolla** [comment]
@the-red  I have the same problem, did you find any solution?

**Comment by LiamAshdown** [comment]
Same here, how do i set my environment variables

**Comment by jamesdaniels** [comment]
.env files are now respected in the latest Firebase CLI release.
