### ISSUE TITLE
Support for Remix

### ISSUE THREAD

**Issue by fahadahmed** [FirebaseExtended/firebase-framework-tools#39]
Hi 👋,

Supporting frameworks like Next, Nuxt etc is really great. Is there support coming for Remix as well?

Currently, going through the latest release, is this something that we can do having a `custom` framework setup?

Thanks in advance.

**Comment by fahadahmed** [comment]
Any help here?

**Comment by johnnyoshika** [comment]
I'm interested in this as well

**Comment by fahadahmed** [comment]
I was hoping this would be an announcement at the Summit. Unfortunately not. Would be great if this is in the works in the next release or so.

**Comment by jamesdaniels** [comment]
We're looking into other frameworks but have no timelines to share. In the meantime we offer two DIY integrations: Vite and Express/custom. 

Vite should "just work" out of box (non-SSR ATM.)

With the express/custom integration we call `npm run build` for you, we look for a `directories.serve` field to your package.json telling us where the static content is after build, and then it will look for an _optional_ express app factory (`export app = () => { return yourExpressApp }`) or a URL handler function (`export handle = (req, res) => { ... }`) exported from your main entry. If the latter is found we'll treat the app as SSR. We be doing work to document all this better in the next few weeks.

**Comment by fahadahmed** [comment]
Umm, I am a bit confused on how to use Vite for Remix built app.

Express/custom integration looks promising. Would need to tinker with the steps provided above. Thanks for the reply @jamesdaniels.

**Comment by jamesdaniels** [comment]
Here's the docs on the custom integration https://firebase.google.com/docs/hosting/express
