### ISSUE TITLE
Next js middleware not working.

### ISSUE THREAD

**Issue by RajendraAVerma** [FirebaseExtended/firebase-framework-tools#42]
I have explained this issue in below link.
 [https://stackoverflow.com/questions/73959286/next-js-middleware-not-working-after-deploy-in-firebase-hosting]()

**Comment by jamesdaniels** [comment]
Thanks for the report. We're looking into supporting middleware soon.

**Comment by awinogrodzki** [comment]
Hey  @jamesdaniels,

This might help when introducing middleware support for Firebase: https://github.com/ensite-in/next-firebase-auth-edge

**Comment by jamesdaniels** [comment]
Middleware support was released in a recent CLI version
