### ISSUE TITLE
[ISR] Revalidate property doesn't work on getStaticProps

### ISSUE THREAD

**Issue by fortulyapps** [FirebaseExtended/firebase-framework-tools#45]
I'm trying to create a page that have static pages but should rebuild the page after some time (using the "revalidate" property). I was testing if is working hosting on Firebase, but that doesn't seems to work properly, because after the first generation, never rebuild again.

Here is the code I used to test:

> export function getStaticProps() {
>     let randomNumber = Math.random();
>     console.log("Random number generated: " + randomNumber);
> 
>     return {
>         revalidate: 10, // secs
>         props: {
>             number: randomNumber,
>         }
>     }
> }
> 
> export default function randomnum(props) {
>     return (
>         <div>
>             <h1>Random number: {props.number}</h1>
>         </div>
>     )
> }

Are you planning to fix this? Maybe with a function similar to the ssr function, but for SSG (where it will check for revalidate properties).

**Comment by jamesdaniels** [comment]
Sorry about that, we missed a TODO while we were moving the code into firebase-tools. We'll get this addressed shortly.

**Comment by jamesdaniels** [comment]
Working on this and the Next 13 fixes here https://github.com/firebase/firebase-tools/pull/5175

**Comment by jamesdaniels** [comment]
Fixed in the latest CLI release
