### ISSUE TITLE
How can I access to currentUser in getServerSideProps of Next.js

### ISSUE THREAD

**Issue by SugiKent** [FirebaseExtended/firebase-framework-tools#51]
ref. https://firebase.google.com/docs/hosting/nextjs#:~:text=This%20can%20be%20accessed%20in%20getServerSideProps

> The Express res.locals object will optionally contain an authenticated Firebase App instance (firebaseApp) and the currently signed-in user (currentUser). This can be accessed in getServerSideProps.

Could you tell me how to access to currentUser in getServerSideProps, Next.js? At first, I thought that I can used it like this.

```
export const getServerSideProps: GetServerSideProps = async (context) => {
  console.log(context.res.locals currentUser);
  return { props: { data: 'aaa' } };
};
```

However I couldn't do it because the `res.locals` is *Express res.locals object*. What is it? And How can I access to it?

**Comment by KartikBazzad** [comment]
Did you find any solution?

**Comment by SugiKent** [comment]
Not yet.

**Comment by SugiKent** [comment]
Is there something fundamentally wrong with my question?

**Comment by jamesdaniels** [comment]
`context.res.locals?.currentUser`

**Comment by KartikBazzad** [comment]
> Locals is just an object, be mindful it might not be present so nullish coalesce `context.res.locals?.currentUser`

Nice explanation, if this was working @SugiKent  wouldn't have created this ticket in the firstplace, i spent two days looking for this, i even  changes the ctx type to get  context.res.locals but id did not give any results

**Comment by SugiKent** [comment]
Sorry, I miss spelled in first comment. I forgot to use `?.`.
Now I implemented below code but `firebaseApp` and `currentUser` were `undefined`.
```javascript
export const getServerSideProps: GetServerSideProps<Props, Params> = async (
  context
) => {
  console.log({ firebaseApp: context.res.locals?.firebaseApp });
  console.log({ currentUser: context.res.locals?.currentUser });

  return {
    props: { aaa: null },
  };
};
```

I thought that these property were not implemented and [the official doc](https://firebase.google.com/docs/hosting/nextjs#optional_integrate_with_firebase_authentication) was advanced, right?

**Comment by SugiKent** [comment]
@jamesdaniels

**Comment by KartikBazzad** [comment]
> 
locals property doesn't exist on context.res;
