### ISSUE TITLE
Dynamic Routes and Middleware Error

### ISSUE THREAD

**Issue by BolajiAyodeji** [FirebaseExtended/firebase-framework-tools#52]
This is probably similar to #42. I deployed a Nextjs project to Firebase hosting (to test the experimental web frameworks support), and some pages that use dynamic routes return a 500 internal server error. When I check the cloud functions error log, I get this error:

<img width="589" alt="Screenshot 2022-11-11 at 7 56 45 AM" src="https://user-images.githubusercontent.com/30334776/201281501-ac68043f-f9f2-4211-ac02-32edacb37990.png">

Any idea what could be wrong, please? Since the function deployed is automatically created during the CLI process.

**Comment by BolajiAyodeji** [comment]
I'm guessing #50 will fix this?

**Comment by jamesdaniels** [comment]
Correct, middleware support is coming between #50 and https://github.com/firebase/firebase-tools/pull/5195
