### ISSUE TITLE
Deployment without functions fails

### ISSUE THREAD

**Issue by ismaelaarab** [FirebaseExtended/firebase-framework-tools#55]
When i try to run `firebase deploy --only hosting`. I get the follwing error: `Error: Your project project-name must be on the Blaze (pay-as-you-go) plan to complete this command. Required API cloudbuild.googleapis.com can't be enabled until the upgrade is complete. To upgrade, visit the following URL:`

The nextjs project has only `_app.js` and `index.js` in it without any dependency also no api directory.

The documentation indicates that if there is no server side logic the deployed would be hosting only:
`If your app includes dynamic server-side logic, the CLI deploys that logic to Cloud Functions for Firebase.` and 
`Apps with dynamic server-side logic must provide a billing instrument during Cloud Functions setup. `

Is it possible to deploy only static without cloud functions and enabling the Blaze plan?

**Comment by jamesdaniels** [comment]
In an upcoming Firebase CLI release (should be out next week) we will console log why we determined a Cloud Function is needed for your Next.js app. The likely culprits: use of the App directory (Next 13), Image Optimization, middleware, or advanced rewrites/redirects/headers in your next.config.js.

We'll be updating the docs with all the reasons why a backend might be needed too.

If you nix those it should deploy a fully static application to Firebase hosting.

**Comment by jamesdaniels** [comment]
Reasons why a backend are needed are now displayed 
![reasons](https://user-images.githubusercontent.com/44975/218880640-ada6a922-a436-4d6a-a076-d37ae5226653.png), you can whittle those down to deploy an entirely static site.
