### ISSUE TITLE
Update PeerDeps 

### ISSUE THREAD

**Issue by Brian-McBride** [FirebaseExtended/firebase-framework-tools#65]
https://github.com/FirebaseExtended/firebase-framework-tools/blob/f9b2ebd7acdd6fc7ad59279b539d187149a2912a/package.json#L63

I keep getting the error: 
```
⚠  functions: package.json indicates an outdated version of firebase-functions. Please upgrade using npm install --save firebase-functions@latest in your functions directory.
```

It looks like all that is being used from firebase-functions is the `Request` type. From `firebase-functions` it is extending the `Express` type.

```typescript
/** An express request with the wire format representation of the request body. */
export interface Request extends express.Request {
  /** The wire format representation of the request body. */
  rawBody: Buffer;
}
```

From that standpoint, I didn't even see `rawBody` used anywhere in the code. Leaving this lib basically using only the base `Express Request` type.

**Comment by Brian-McBride** [comment]
# Problem: Outdated NPM deps

## Error

This error still blocks deployment: 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sk-t3@0.1.0
npm ERR! Found: firebase-functions@4.3.1
npm ERR! node_modules/firebase-functions
npm ERR!   firebase-functions@"^4.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-functions@"^3.23.0" from firebase-frameworks@0.7.0
npm ERR! node_modules/firebase-frameworks
npm ERR!   firebase-frameworks@"^0.7.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

The current version is `"firebase-functions": "^4.3.1",`

As mentioned earlier, the only thing that is imported from the `firebase-functions` package that I can find is the use of the `Request` type. But it doesn't even need to, as it never uses the extended `rawBody` object in the repo anyway. 

## Suggested solution

Remove the hard dep on `firebase-functions` altogether. Drop it in as a dev-dep or peer-dep with "*" as it is ONLY used for compiler typing, which the consumer won't use anyway. 

It should just be a dev dependency, as it is only used for type inference.

**Comment by jamesdaniels** [comment]
We've bumped the version of firebase-functions in a recent release, thanks.
