### ISSUE TITLE
Can I request a minimum instance with the nextjs SSR function generated during deployment?

### ISSUE THREAD

**Issue by vp-walter** [FirebaseExtended/firebase-framework-tools#77]
I love the nextjs deployment with firebase. Thank you for the rapid pace at which you guys are improving this feature.

I searched the docs and github but I couldn't find anything on how to configure a minimum instance for the SSR function created by the web framework deployment. Is that possible? The function cold start time is quite bad for us. I know this is because of how many packages are being bundled and loaded. In the meantime configuring a min-instance would help with the performance.

**Comment by jamesdaniels** [comment]
Glad you're enjoying our work!

We need to document this but you can now configure the code-generated Cloud Function with `frameworksBackend` in your `firebase.json`. It should take all the same options as [onRequest](https://firebase.google.com/docs/reference/functions/2nd-gen/node/firebase-functions.https.httpsoptions.md#httpshttpsoptions_interface). E.g,

```json
{
  "hosting": {
    "source": ".",
    "frameworksBackend": {
      "region": "us-central1",
      "minInstances": 1,
      "maxInstances": 10,
    }
  }
}
```

**Comment by vp-walter** [comment]
that worked. awesome, thank you.
