### ISSUE TITLE
Auto-generated Cloud Function cannot be configured

### ISSUE THREAD

**Issue by ErikWittern** [FirebaseExtended/firebase-framework-tools#9]
The Cloud Function being created for server-side rendering (of a Next.js app in my case) seems to be deployed to region `us-central1` by default, and seems to have 256 MB of memory allocated.

Is it possible to configure these aspects?

**Comment by abMarlim** [comment]
+1

**Comment by jamesdaniels** [comment]
At the the moment we don’t allow any configuration of the cloud function. We’re thinking through what that would look like. 

Thanks for giving things a spin.

**Comment by jamesdaniels** [comment]
Once [d6826ee](https://github.com/firebase/firebase-tools/commit/d6826ee9e9c2dc5b8e320953aa794be7ba2fdcdb) lands in the next CLI release you'll be able to configure the generated Cloud Function via firebase.json (hosting.frameworksBackend)

**Comment by jamesdaniels** [comment]
We'll have to update the docs, there are now a few regions you can rewrite from.
